name: Run Integration Tests

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        description: 'Release version'
        required: true
      s3_bucket_prefix:
        type: string
        description: 'Bucket prefix for SAM assets'
        required: true
      aws_region:
        type: string
        description: 'AWS region to run tests in'
        default: 'us-west-2'
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: 'Release version'
        required: true
      s3_bucket_prefix:
        type: string
        description: 'Bucket prefix for SAM assets'
        required: true
      aws_region:
        type: string
        description: 'AWS region to run tests in'
        default: 'us-west-2'

env:
  AWS_REGION: "${{ inputs.aws_region }}"
  SAM_CLI_TELEMETRY: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Download SAM manifests
      run: |
        make integration
      env:
        S3_BUCKET_PREFIX: "${{ inputs.s3_bucket_prefix }}"
        RELEASE_VERSION: "${{ inputs.release_version }}"
