on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
    inputs:
      release_version:
        type: string
        description: 'Release version to use. If omitted, version will be computed'
        default: ''
  workflow_dispatch:
    inputs:
      run_integration_tests:
        type: boolean
        description: 'Run integration tests'
        default: true
 
jobs:
  tests:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_integration_tests }}
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  upload:
    needs: tests
    uses: ./.github/workflows/upload.yaml
    secrets: inherit
    with:
      s3_bucket_prefix: "observeinc-"
      global: ${{ github.event_name == 'workflow_dispatch' }}
      release_version: ${{ inputs.release_version }}

  integration:
    needs: upload
    uses: ./.github/workflows/integration.yaml
    secrets: inherit
    with:
      s3_bucket_prefix: "observeinc-"
      release_version: ${{ needs.upload.outputs.release_version }}
